name: cantara
version: '2.4.0'
summary: A Song Presentation Software.
description: |
  A simple, leightweight but powerful program for song presentation in churches, small groups or at karaoke parties.
confinement: strict
icon: app.cantara.Cantara.png
base: core20
grade: stable

architectures:
  - build-on: [amd64, arm64]

plugs: # plugs for theming, font settings, cursor and to use gtk3 file chooser
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes:sounds-themes

parts:
  lazarus:
    plugin: nil
    source: .
    source-type: local
    build-packages:
    - wget
    - libgtk2.0-dev
    override-build: |
      wget -nc https://downloads.sourceforge.net/project/lazarus/Lazarus%20Linux%20amd64%20DEB/Lazarus%202.2.2/lazarus-project_2.2.2-0_amd64.deb
      wget -nc https://downloads.sourceforge.net/project/lazarus/Lazarus%20Linux%20amd64%20DEB/Lazarus%202.2.2/fpc-laz_3.2.2-210709_amd64.deb
      wget -nc https://downloads.sourceforge.net/project/lazarus/Lazarus%20Linux%20amd64%20DEB/Lazarus%202.2.2/fpc-src_3.2.2-210709_amd64.deb
      apt install ./lazarus-project_2.2.2-0_amd64.deb ./fpc-laz_3.2.2-210709_amd64.deb ./fpc-src_3.2.2-210709_amd64.deb
    prime: [-*]
  cantara:
    after: [lazarus]
    plugin: nil
    source: .
    source-type: local
    build-packages:
    #- fpc
    #- lazarus
    #- lcl
    #- lcl-utils
    - build-essential
    - libqt5pas-dev
    - libqt5pas1
    stage-packages:
    - libqt5pas1
    - qt5-gtk-platformtheme

    override-build: |
      cd src
      lazbuild -B --bm="Release" --ws="qt5" Cantara.lpi
      cp -r languages $SNAPCRAFT_PART_INSTALL/
      install Cantara.ico $SNAPCRAFT_PART_INSTALL/
      install cantara $SNAPCRAFT_PART_INSTALL/
      cd ..
      install cantara.desktop $SNAPCRAFT_PART_INSTALL/
      install app.cantara.Cantara.png $SNAPCRAFT_PART_INSTALL/
    stage:
    - lib
    - usr
    - etc
    - cantara
    - languages
    - cantara.desktop
    - Cantara.ico
    - app.cantara.Cantara.png
  cleanup:
    after: [cantara]
    plugin: nil
    build-snaps: [kde-frameworks-5-91-qt-5-15-3-core20]
    override-prime: |
      set -eux
      for snap in "kde-frameworks-5-91-qt-5-15-3-core20"; do  # List all content-snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
      done
      for cruft in bug lintian man icons; do
        rm -rf $SNAPCRAFT_PRIME/usr/share/$cruft
      done
      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
      find $SNAPCRAFT_PRIME/usr/lib -type f,l -name 'libQt*.so*' ! -name 'libQt5Pas*.so*' -delete

apps:
  cantara:
    adapter: full
    extensions:
      - kde-neon
    command: cantara
    desktop: cantara.desktop
    environment: 
      DISABLE_WAYLAND: 1
    plugs:
    - home
    - desktop
    - desktop-legacy
    - opengl
    - x11
    - unity7
    - wayland
    - gsettings
