on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [windows-latest,ubuntu-latest,macos-latest]
        lazarus-versions: [stable]
    steps:
    - uses: actions/checkout@v2
    - uses: gcarreno/setup-lazarus@v3.2
      with:
        lazarus-version: "stable"
        #include-packages: "lib"
        with-cache: false
    - name: Build the Windows Application
      if: ${{ matrix.operating-system == 'windows-latest' }}
      run: lazbuild -B src/Cantara.lpi
    - name: Install libqt5pas dependency under Ubuntu
      if: ${{ matrix.operating-system == 'ubuntu-latest' }}
      run: sudo apt-get -y install libqt5pas-dev libqt5pas1
    - name: Build the Linux Application
      if: ${{ matrix.operating-system == 'ubuntu-latest' }}
      run: make
    - name: Build the MacOS Application
      if: ${{ matrix.operating-system == 'macos-latest' }}
      run: lazbuild -B src/Cantara.lpi
    - name: Artifacts (Linux)
      if: ${{ matrix.operating-system == 'ubuntu-latest' }}
      uses: actions/upload-artifact@v3
      with:
        name: Compiled Linux Binary
        path: |
          cantara
          src/languages
          src/Cantara.ico
          app.cantara.Cantara.desktop
          app.cantara.Cantara.png
          COPYING
    - name: Artifacts (Windows)
      if: ${{ matrix.operating-system == 'windows-latest' }}
      uses: actions/upload-artifact@v3
      with:
        name: Compiled Windows Binary
        path: |
          src/cantara.exe
          src/languages
          src/Cantara.ico
          app.cantara.Cantara.desktop
          app.cantara.Cantara.png
          COPYING
    - name: Artifacts (Apple)
      if: ${{ matrix.operating-system == 'macos-latest' }}
      uses: actions/upload-artifact@v3
      with:
        name: Compiled Mac OS Binary
        path: |
           src/cantara.app
           COPYING
